#build and deploy
steps:
  - name: alpine
    args: ['/bin/bash', 'env']
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/badge-260212/citatenfront', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/citatenfront']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'citatenfront', '--image', 'eu.gcr.io/badge-260212/citatenfront:latest', '--region', 'europe-west4', '--platform', 'managed', '--concurrency', '80', '--max-instances', '10', '--memory', '128Mi', '--timeout', '30s', '--allow-unauthenticated', '--async']
